### ISSUE TITLE
Feature ideas.

### ISSUE THREAD

**Issue by tomtom13** [Gh61/lovelace-hue-like-light-card#1]
Hi, if I could suggest something, I think it would be helpfull to implement following to make user experience slightly better:
- a right hand side drop down which can be populated with predefined scenes
- a palette button to allow user to select colour on the whim. 
- tap action light toggle (as an config option)

**Comment by tomtom13** [comment]
Well, the problem with with HA is that "clicking" at the card doesn't take people to nicelly polished room configuration where user can have a blast - due to that stuffing some extra options into an entity might have some milage in the tank.

**Comment by malkie-hass** [comment]
Hey,
I really like the card but I’m missing the color and temperature picker. Would love to see this in a future update. Great job so far

**Comment by Gh61** [comment]
Thank you.
I am also missing this feature, so it's my number 1 priority right now.

**Comment by Gh61** [comment]
I believe every missing feature is resolved in the current [Release](https://github.com/Gh61/lovelace-hue-like-light-card/releases/tag/v1.4.0).
