### ISSUE TITLE
Add hue light slider to scene pages

### ISSUE THREAD

**Issue by cas112358** [Gh61/lovelace-hue-like-light-card#10]
Is it possible to add the lights slider / buttons to the scene page that pops up.

This is similar to the functionality you get with the hue controls. 

I can see there is a stub that looks like it might be starting to do that already.

**Comment by Gh61** [comment]
I am planning on adding complete light functionality on `hue-screen`, together with possibility to change color of individual lights, turn them off and so on.

This will take some time for me to do, so maybe it's not a bad idea to add light switches as the first step in some of the upcoming versions befo the full functionality will be available.

**Comment by cas112358** [comment]
Hi,

I would be happy to help you with this if possible.

Do you have a guide on what dependancies are required to build this locally?

Thanks
Carwyn

**Comment by Gh61** [comment]
For the full functionality I am planning to develop entirely  new hue-like multiple color-picker component (I have some private WIP project), so i'd like to keep this on me.

But if you want to contribute on the light tiles, there's nothing stoping you.

You just need **VS code** and **npm**, so you can restore all dependencies and build the project.
For debugging I am using [Live Server extension](https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer) so I can host the result locally and test it on my HA.

_I am pretty new to this environment, so this might not be the best dev stack, but it's working for me._

**Comment by cas112358** [comment]
Hi,

Great thanks.

**Comment by Gh61** [comment]
I see, you had forked the repository and probably setup the environment.

Please write a comment here, if you make any major progress.
I don't want to waste your time, but also don't want relay on your progress.

Thanks for your understanding

**Comment by cas112358** [comment]
Hi,

I have forked and tried to build the project. But when I roll up into the
.js file I get a file that is twice the size of your js file and home
assistant doesn't find the card once I have installed it via the custom
repository in hacs.

But if I figure that out I will comment any progress back here.

**Comment by Gh61** [comment]
The size is correct for the dev version as it is not minimized.
Once you install the dev version of the card you must use the `-test` postfix.
As in `type: custom:hue-like-light-card-test`

Is suggest to use some local server hosting ([Live Server extension](https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer)) and add the `http://localhost:XXX/dist/hue-like-light-card.js` to your [Lovelace Resources manually](https://github.com/Gh61/lovelace-hue-like-light-card#manual).
As it is much faster, than using releases to update after every change.

**Comment by cas112358** [comment]
Great thanks, I will give it a go.

Thanks
Carwyn

**Comment by Gh61** [comment]
Hi
I appreciate the time you put into this.
I saw your screenshots and commits and I see you have added sliders and also changed some other things to your likings.

Sorry to say this, but I have a little different vision for light controls on `hue-screen` and I also want to make much more configuration options for the description (sub-title) on card. Also my ego little bit kicks in and I kinda want to make these crucial parts myself (this was the reason for me to even start working on this).

Hopefully your forked card now provides the functionality, you were looking for.
And I see similar functions coming to this version soon.

**Comment by cas112358** [comment]
Hi,

No problem, completely understand.

I will keep an eye on your progress.

Thanks
Carwyn

**Comment by Gh61** [comment]
Resolved in the current [Release](https://github.com/Gh61/lovelace-hue-like-light-card/releases/tag/v1.4.0).
