### ISSUE TITLE
Not every user see custom

### ISSUE THREAD

**Issue by hugopurmer** [Gh61/lovelace-hue-like-light-card#104]
My wall-pad cant’t see de custom card. On my phone it works. 

Why is that and how can I resolve this?

thanks for you’re help.

![IMG_4890](https://github.com/Gh61/lovelace-hue-like-light-card/assets/83445669/0f8ddb82-57c9-4829-89be-06bd1b3bdf4b)
![IMG_4889](https://github.com/Gh61/lovelace-hue-like-light-card/assets/83445669/fb54428e-32f5-47b2-b536-5f6fdaadb16c)

**Comment by Gh61** [comment]
I believe this is more of a general issue.
After you install new card, you need to refresh your browser's cache (typically by `Ctrl + F5`).
I don't know, how are you loading the home assistant on your wall-pad, but if it's an application, you can restart it. Maybe even restart your device, if you don't have other options.

**Comment by Gh61** [comment]
Any progress?
I suspect two things might have caused this.
1. the script is not loaded correctly (maybe problem with location of the script?). Did you install it using HACS?
2. there's something in the script, that is not supported by the browser engine on your Android tab. This can create some error, that will cause the card not load. I don't know, if is somewhat possible to show log in the application, or show the log at least in some browser on the Android. Maybe you can try to look into home assistant logs, if there is some error.

**Comment by Gh61** [comment]
I believe this is already resolved. Feel free to reopen, if the error still occurs and you think it is related to this card.
