### ISSUE TITLE
Icon arrangement

### ISSUE THREAD

**Issue by oliver073** [Gh61/lovelace-hue-like-light-card#105]
Hello, first of all thank you for your great work! This is exactly what I was looking for.

I only have two "little" suggestions for improvement:

1. Why are multiple lights always in a row? I have some rooms with over 10 lights. Including light groups even more. But they don´t stack up like scenes in two ore more rows.
That's a lot to scroll sideways - especially on a smartphone.
2. Light groups can currently only be added to the lights. Maybe a separate “light group” would help. So one area each for scenes, lights and light groups.

And two questions:

Can I hide scenes individually or completely, even they are in the corresponding area? I don´t need all scenes in every room.
Can I change the size of icons for lights and scenes?

Thanks in advance.
Greetings, Oliver

**Comment by Gh61** [comment]
Hi, thank you for kind words.

To answer your questions/suggestions:
1) The main goal of this project is to make the user experience as similar to official Hue app, as possible. So the two row scenes plus one row lights design is recreated based on official hue app:
![Hue app screenshot](https://github.com/Gh61/lovelace-hue-like-light-card/assets/10837736/303db9d2-04b7-45ec-b243-5d22e12debdd)
2) If I get your question correctly, this is also proposal to change the design of hue-screen. So the answer is same as no. 1.
Also managing multiple different designs of the dialog would be mess, so I'd rather keep it simple with the one 'original' design.

3) You have two options from which to choose:
- let the scenes load automatically based on area of lights
- configure the scenes manually with `scenes:` option - [Scenes configuration](https://github.com/Gh61/lovelace-hue-like-light-card#scenes-configuration)

4) Changing icon size(s) in hue-screen is not possible for now. Are you having some issue with the current size?

**Comment by oliver073** [comment]
Thank you for your quick reply.
I understand points 1 and 2.
It's probably also not possible to insert a manual line break in yaml after, for example, 4 lights?
I tried a bit but didn't succeed.

3. Is it possible to not display any scene area at all?

4. No issue - it was just an idea.

**Comment by Gh61** [comment]
No, not even the manual line break possible (and the dialog is not prepared for it either).

3. Yes, I thought it should be possible with: `scenes: []`, but as I just discovered, it will still load the scenes automatically (so there is a little bug - I'll fix it in future release).
As a workaround you can use something like this: `scenes: [scene.nothing]`

In this case you will still get the "My scenes" header in the dialog.

**Comment by oliver073** [comment]
OK, thank you!

**Comment by Gh61** [comment]
I fixed the `scenes:[]` configuration option.
And for this case, the "My scenes" title will not be visible.
This will be in the next release.

**Comment by oliver073** [comment]
Cool, thank you!
