### ISSUE TITLE
Add/Fix support for non-dimmable lights

### ISSUE THREAD

**Issue by hofdev** [Gh61/lovelace-hue-like-light-card#11]
For lights controlled with  Philips hue plug is it in the Philips Hue app not possible to change the brightness of the light. The slider bar is for that reason not shown. 
These lights in Home Assistant using lovelace-hue-like-light-card will have a slider which does not work as that isn’t supported. Suggestion to hide the slider based on the device type (Hue smart plug (LOM007)) or via a configuration setting.

**Comment by Gh61** [comment]
Hi, thank you for reporting.
Unfortunatelly I don't have any of these plugs or any light, that has no ability to change brightness.
Can you please post screenshot of attributes for this entity?

When you open your **HA**, go to **Developer Tools**, then **States** and **search** for your hue plug **light**.
**Click** on it to open **detail** of the entity and make me a printscreen of **attributes**.
It should look something like this:
![image](https://user-images.githubusercontent.com/10837736/217230108-8b4b6fd8-3378-4180-a918-68d4ad52aef0.png)

**Comment by hofdev** [comment]
Here the requested settings:

![image](https://user-images.githubusercontent.com/123699966/217331562-083e0f49-9c53-4408-a64f-97d884c66265.png)

A zone in the hue app where this plug is part of (no other lights) will be shown like this without the slider.

![image](https://user-images.githubusercontent.com/123699966/217332181-83a12a74-d23f-457a-bc06-223f2a4dae0c.png)

Hope this helps.

**Comment by hofdev** [comment]
Thank you for the quick fix, works as expected.
