### ISSUE TITLE
Bug/Feature Request: Lights do not react to Scene changes fast enough.

### ISSUE THREAD

**Issue by forgenator** [Gh61/lovelace-hue-like-light-card#118]
Hi, I've just installed Home Assistant, and have moved from Philips Hue to HA completely. Using this hue-light cards was a god send so that we can easily build a dashboard that mimics the functionality of Hue -app, while enjoying everything else. 

The sad problem i've noticed, is that the cards are somewhat slow to update, or do not update at all. 
* If i update the lights using a predefined Scene, the actual cards in the dashboard stay the same color as before, until i press somewhere in the dashboard, after which all cards update. 
* If i modify the lights using the slider in the dashboard, the other cards react, better, but not always instantly.
* If i go into the scene selection, and modify the lights using the the lights under the scene selection, then they all react instantly. 

This makes the whole experience rather difficult, because the cards do not reflect the actual state of the lights. You have a "Coming soon feature" in your readme.md: "faster reactions between multiple cards (instant change of value on other cards)". So i was wondering, what is the status, or is this an issue you are aware? :thinking: 

And just to inform, if i add something else, like "Custom: Slider Card" the reaction is instant on all light entities. So i'm certain it is just this addon that has some issue with receiving information/updating information from the Zigbee network. The problem of course, stems that i like the UI and Scene usage of this addon.

Information:
* Raspberry pi 5 8GB
* Home Assistant - Container - Host Mode
* Using ZHA integration, all lights have been added to ZHA, one group "all lights" created as ZHA group.

Versions:
    Core 2023.11.2
    Frontend 20231030.2

**Comment by Gh61** [comment]
Hi, you're right.
As you said, this is a bug that I'm aware of.

There are multiple issues at once.
- updating light attributes after scene activation seems to be the hardest one. In my experience some (simpler) scenes are updating light values almost instantly, other scenes are taking some time to update values (not only in my card).
    - I'd still like to take a look on this
- reaction of other hue-cards on slider change - this is exactly the feature I'd like to implement

All in all, I'll have to revisit and maybe rewrite caching of set values and take a look on possibilities to load light attributes faster after scene activation.

Sadly I keep pushing this bug/feature more and more to the future, as requests for another features are coming.

But thank you for your interest, this raised the importance of this issue.

**Comment by DerPicknicker** [comment]
@forgenator ... 

Firstly I created normal groups inside HA. But today I switched to ZHA-Groups and the response-Time is awesome nearly real-time. Only the Animation is for my favour to slow. I will create for this an additional Issue. 

Anybody how is not using ZHA-Groups you should migrate its really mindblowing. Before that I had some sync issues with the color I set and the light are updated. But now all these issues are gone....

**Comment by Gh61** [comment]
- Fixed the issue with time-cache (card updating later than other cards).
- Added the instant change feature (all hue-cards will react to changes in other hue-cards instantly when the change happens).
- Color detection from activated scene - this is still dependent on how fast the HA register color change on affected lights

Will be in the next Release
