### ISSUE TITLE
Scene sorting

### ISSUE THREAD

**Issue by malkie-hass** [Gh61/lovelace-hue-like-light-card#12]
Hi,
I use the automatic detection of scenes. They seem to be added in a random order. Is there some possibility to sort them somehow or would that something that could be added?

thanks a lot

malkie

**Comment by Gh61** [comment]
Hi, I'll look into some sorting option for scenes. Thank you for suggestion.

**Comment by Gh61** [comment]
Hi, I've reviewed the order in which automatically detected scenes are shown and I've also added option to make them alphabetically sorted.
See [Scene detection](https://github.com/Gh61/lovelace-hue-like-light-card#scenes-detection).

This feature will be available in the next v1.5.0 release
