### ISSUE TITLE
Feature Request: Add entity_picture as a scene parameter

### ISSUE THREAD

**Issue by kwbeck** [Gh61/lovelace-hue-like-light-card#126]
Great card!  Exactly what I had been looking for.  Very much appreciate the work you've put into this.

One request.  

Would it be possible to add an option for using an entity_picture in the scene parameters?

I have been using the method/resources below to add the Hue scene pictures to the scene entities in HA, but in HA terms, they are "entity_pictures", not icons, so aren't pulled into the Hue-Like Light Card.

https://github.com/mattmon/hue-scene-icons

Examples from my HA setup:

![image](https://github.com/Gh61/lovelace-hue-like-light-card/assets/98544743/d2af9329-052e-4d73-bda8-023da4a34448)

vs:  

![image](https://github.com/Gh61/lovelace-hue-like-light-card/assets/98544743/3ea50d2e-4a7c-4eff-be38-efcee62cad10)

**Comment by Gh61** [comment]
Nice setup here.

I've never noticed the `entity_pictures` attribute in scene entity.
I'll definitely add support for this as soon as possible.

I'd also like to do some "autodetection" of these images for scenes, so thank you for pointing out interesting project.

**Comment by kwbeck** [comment]
Excellent news!  Thank you very much.

**Comment by Gh61** [comment]
Will be in the next release

**Comment by kwbeck** [comment]
Updated and works like a charm!  Many thanks for the (quick!) update.



![image](https://github.com/Gh61/lovelace-hue-like-light-card/assets/98544743/c9861dbb-9d97-4288-9f57-99d5eb620305)

**Comment by kwbeck** [comment]
Not purely manual, but it does involve a few steps.  Here's the background:

I had found a link to a "hue-scene-icons" project on GitHub that enables this for HA generally, and was using it, but at the time the lovelace-hue-like-light-card didn't support the necessary "entity_picture" attribute.

I then suggested to @gh61 that he add support for the entity_picture attribute so that this card could support the scene icons.  He (very quickly) added that functionality in the latest release.    (Thanks again!)

Check the "Scene Configuration" section in his [README](https://github.com/Gh61/lovelace-hue-like-light-card#readme) file (screenshot below).  He links to that "hue-scene-icons" project which provides the icons and the instructions to add them as a global customization to HA.   

Once this is done, the icons (FYI, they are actually "entity_picture" pictures in HA terms, not true icons) will appear in both the HA Scene entity entries as well as in this card.  

FWIW, my experience was that to get this to work, I needed to reboot HA after downloading/installing the pictures and manually clear cached images in my browser.

Screenshot:

![image](https://github.com/Gh61/lovelace-hue-like-light-card/assets/98544743/46983e2d-a02f-4eee-bcac-b4fb651f2be9)

**Comment by Greenphlem** [comment]
@kwbeck Hey! I was able to follow those instructions but after running the hue_scene_selector.yaml automations, my scenes are just blank icons: 

<img width="597" alt="image" src="https://github.com/Gh61/lovelace-hue-like-light-card/assets/3390436/e35bae82-b306-4b71-b073-bdb1646cfd7e">

I have tried to reboot HA, My RPi, and try in incognito. Any suggestions?

**Comment by Gh61** [comment]
I think it might be the case that you forgot to upload the images to your RPi, or they are not in the correct directory.
If you set the `customize_glob` to this
```yaml
scene.*read:
  entity_picture: /local/hue_scene_icons/read.png
```

You have to upload the file `read.png` into the `/homeassistant/www/hue_scene_icons` directory.

**Comment by kwbeck** [comment]
@Greenphlem, I think @Gh61 's comment is the most likely solution to the problem you're seeing, but if not, then try manually clearing cached images in your browser. That's what solved the problem for me.

**Comment by Greenphlem** [comment]
Yep, you're both right! I had it in /www/community because that where all the HACS stuff was. I edited my YAML to point there and it's all working now. Thank you both <3 

<img width="605" alt="image" src="https://github.com/Gh61/lovelace-hue-like-light-card/assets/3390436/3e7860f3-7c3e-46c2-9abd-b636079642af">

**Comment by RedwoodNL** [comment]
I feel like a total n00b again. 
What exactly did you do to get the images? I'm missing the steps.
Do i need to add a customize.glob file and put code into it?

Thanks


> Yep, you're both right! I had it in /www/community because that where all the HACS stuff was. I edited my YAML to point there and it's all working now. Thank you both <3
> 
> <img alt="image" width="605" src="https://private-user-images.githubusercontent.com/3390436/291661340-3e7860f3-7c3e-46c2-9abd-b636079642af.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzI1NTUyMzQsIm5iZiI6MTczMjU1NDkzNCwicGF0aCI6Ii8zMzkwNDM2LzI5MTY2MTM0MC0zZTc4NjBmMy03YzNlLTQ2YzItOWFiZC1iNjM2MDc5NjQyYWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTEyNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMjVUMTcxNTM0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmJlMGRkMzQwYzk4MzFkZWE4ODI4NGFlODc5YmVlNmQxYjBiNTA0OTQ1N2FkNmM5YzYzZDgwYmJlZGE2NzUxNiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.ucuSVwV4851t1hR0BGux0Qq1ZcneMKjyB8oYiNy-dXQ">

**Comment by SirHades** [comment]
If anyone is looking into this... I just spend too long searching why it did not work and this is what I had wrong :
Copy the images from the Hue-scene-icons github into your www directory (/www/hue_scene_icons/)
Then edit your configuration.yaml in studio code server. either after "homeassistant" or if, like in my case it's not there, at the end add :
homeassistant:
  customize_glob:

Then copy the whole text (scene.*adrift:       entity_picture: /local/hue_scene_icons/adrift.png) and so on. Don't forget to ident.
Restart homeassistant, not just quick reload.
And I suddenly had all my icons.

I didn't know I had to have a homeassistant bit before customize_glob.

Hope this helps someone.
Thank you @Gh61 This card is amazing.
