### ISSUE TITLE
Feature: add double click actions

### ISSUE THREAD

**Issue by Altosaxophony** [Gh61/lovelace-hue-like-light-card#128]
Hello, i cant get the onHoldAction and offHoldAction to work.

I use this card in Dwains Dashboard:

type: custom:hue-like-light-card
entity: light.buro
offClickAction: turn-on
offHoldAction: hue-screen
onClickAction: turn-off
onHoldAction: hue-screen

It works well for the ClickAction but when i hold, nothing happens. When i release from holding, it does the click action instead of popping up the hue-screen.

Anyway i am not happy with the Actions. Instead of "Hold" i need a double Tap action here.  I also cannot get this to work:

double_tap_action:
..action: more-info

I think i am misunderstandig or doing something wrong : )
Thank you for your help

**Comment by Gh61** [comment]
Hi HoldActions are not released yet.
They're introduced in version 1.6.0 which I'm currently working on and plan to release in about a week.
Thank you for understanding.

As of double click - The hold actions would not be sufficient?

**Comment by Gh61** [comment]
There are many missing features around actions, so I created summary issue, which I'd like to implement at once.
See [#167 - Extend and standardize actions](https://github.com/Gh61/lovelace-hue-like-light-card/issues/167)
