### ISSUE TITLE
Allow `call-service` for action

### ISSUE THREAD

**Issue by Emyrk** [Gh61/lovelace-hue-like-light-card#131]
Right now only `'default', 'none', 'turn-on', 'turn-off', 'more-info', 'scene', 'hue-screen'` are supported for actions.

`call-service` should be added to make a click to do something else entirely.

**Comment by Gh61** [comment]
Thank you for suggestion, actually there are many missing features around actions, so I created sumarry issue, which I'd like to implement at once.
See [#167 - Extend and standardize actions](https://github.com/Gh61/lovelace-hue-like-light-card/issues/167)
