### ISSUE TITLE
Not seeing individual lights in Hue Screen

### ISSUE THREAD

**Issue by bmcclure** [Gh61/lovelace-hue-like-light-card#14]
I think I may be misunderstanding some setup step, but so far I'm unable to get individual lights to appear in the Hue Screen.

For example, this is a card I'm testing:

```
type: custom:hue-like-light-card
title: Living Room Lights
entities:
  - light.living_room_ceiling_light
  - light.living_room_hue_iris_1
  - light.living_room_hue_iris_2
  - light.entertainment_center_lights
  - light.tv_lights
onClickAction: hue-screen
offClickAction: hue-screen
hueBorders: false
offColor: theme-color
hueScreenBgColor: theme-color
offShadow: false
```

When the Hue Screen opens, I see the main slider and toggle at the top, and then I see the list of scenes associated with those lights, but there is no list of lights with toggles underneath that as the screenshots show.

Is there something extra I need to do to enable that functionality?

**Comment by Gh61** [comment]
Please, try to look into the console of your browser (typically press F12 and select the Console tab). I think, there might be some kind of error here.
You can also try to remove some lights from `entities` to detect if it is working with some of them (even left only one of these lights).

**Comment by bmcclure** [comment]
I realized that even though HACS said I had version 1.3.0, it seems I was either still using the previous version, or maybe had a front-end cache issue. I re-downloaded it with HACS, reloaded the cache, and the lights appeared!

Sorry for the false alarm, it's working great!
