### ISSUE TITLE
Add `navigate-to` action

### ISSUE THREAD

**Issue by fetzerch** [Gh61/lovelace-hue-like-light-card#140]
It would be nice if being able to set an action to `navigate to` a different dashboard path.

**Comment by Gh61** [comment]
Thank you for suggestion, actually there are many missing features around actions, so I created sumarry issue, which I'd like to implement at once.
See [#167 - Extend and standardize actions](https://github.com/Gh61/lovelace-hue-like-light-card/issues/167)
