### ISSUE TITLE
Brightness in text templates is shown as integer 1-255, not as percent value

### ISSUE THREAD

**Issue by pskovalko** [Gh61/lovelace-hue-like-light-card#150]
Brightness in text templates is shown as integer 1-255, not as percent value. For example:

description: Lights {{ light.frontlights.brightness }}

![image](https://github.com/Gh61/lovelace-hue-like-light-card/assets/134014798/216e420a-414c-46a6-93d4-b6e35e76de8a)

In your documentation brigthness in name and descritption fields on sample screenshots is shown as percent value, which contradicts with my experience. Is there any way to fix it, so it is shown as percent value.

**Comment by Gh61** [comment]
Hi,

this should be working (and is working on my instance).
What version of HA and this card (can be seen in console of your browser - open with F12) do you use?

HA version must be 2023.9+ and card version must be 1.5.0+.

Also, as this is related to localization, what language for UI do you use?

**Comment by pskovalko** [comment]
The card is 1.6.0, but HA is 2023.4.6, which is probably the problem. Thank you very much for quick reply. Closing the issue.
