### ISSUE TITLE
Popups no longer work on iPad & Fire Tablet HD10/Android

### ISSUE THREAD

**Issue by snapjack** [Gh61/lovelace-hue-like-light-card#151]
Hello,

since yesterday the hue popup does no longer work on my IPad pro and my Fire HD10 Tablets.
Symptoms: 
- IPad: If you tap on the card, the popup flickers for a millisecond, but does not stay on top  (Update: worked again after restart of the IPad)
- Fire HD10: You see the reload of the page if you look at the favicon, but nothing happens
- Chrome or Safari on Mac: Works as designed

I really do not know what changed...

**Comment by Gh61** [comment]
I think something must have changed on your HA. I am using the latest version of HA and this card and everything works fine.
I don't have any of the devices you mentioned, but I've tested it on some phones I have around and it works fine.

Maybe you updated something? Or installed new card/integration/addon yesterday, that caused the trouble?

**Comment by snapjack** [comment]
Yeah, thought about that. So I restored the full backup of yesterday => no success. Restored the full backup of 4 days ago with the 12.2 release of HA Core => no success. So in the moment I do not know what might have changed... 

It also does not help to use the
        offClickAction: hue-screen
        onClickAction: hue-screen

But at least if I use 
        offHoldAction: hue-screen
        onHoldAction: hue-screen
the popup displays when pressing the card longer...

**Comment by stelbean** [comment]
I am experiencing this same issue on all of my android tablets, whether I use the HA app, chrome or fully kiosk. However I noticed on one of my dashboards the hue-like-card's were working ok and another they were not and isolated the difference - any dashboards using grid-layout didn't work, any using the default masonry layout worked fine.  All of the cards worked fine in all dashboards when accessed from chrome on windows.  

On the non-working dashboards clicking on the card quickly/repetitively the odd time the hue-screen popup would randomly show up, but it was rare and I couldn't decipher any pattern that would make it show up.

As per snapjack's comment - I am using the onHoldAction: hue-screen as a workaround for the time being

**Comment by Gh61** [comment]
Thank you for elaboration.
Can you please post your yaml configuration of the layout and card.

I'll be grateful if you can provide more information on this bug.
Can you test it on Android phone? Does it work? Does it work on PC browser (Chrome)?
Do you have any errors related to this in HA logs?

**Comment by Cmo2788** [comment]
Was going to start a new topic about this but seen @stelbean is having a similar issue to mine so i posted here instead. here is a little more info about my specific issue @Gh61 if you want i can open a new topic.

Currently works on Mac (Chrome), PC (OGX), Android (Zfold3 and 4 both with the latest android App and browser)
None of my apple mobile devices (using the app) will allow the popup to come up ONLY on my home screen, if i click on my test page where i have some base codes for testing layouts etc. the pop up opens up just fine.

The page that i cannot get any of the popups to work on is in a grid card, but even adding a new card and setting up the popup still just brings up the default HA light control card. 

I am at work at the moment so i cannot get any screenshots but as soon as i get home i can grab a few if it will help. 


Here is the YAML for the card that is NOT working on the apple devices.

type: custom:hue-like-light-card
title: Front Porch
theme: ios-dark-mode
entities:
  - light.front_porch_light_1
  - light.front_porch_light_2
  - light.hue_color_lamp_1_3
  - light.front_yard_cam_floodlight
slider: mushroom
scenes: null
hueBorders: true


and here is the YAML for the one that does work on Apple devices

type: custom:hue-like-light-card
title: Front Porch
theme: ios-dark-mode
entities:
  - light.front_porch_light_1
  - light.front_porch_light_2
  - light.hue_color_lamp_1_3
  - light.front_yard_cam_floodlight
slider: mushroom
scenes: null

**Comment by jcsharp** [comment]
I have the same problem using touch on Windows: the popup opens with a mouse click but not with a tap of my finger.

**Comment by Gh61** [comment]
Thank you all guys, I've finally figured out, what is causing this issue and I'll try to make version, that fixes this as soon as possible.

In the last version I've started using hammerjs for clicks and long-presses on card and on tiles in hue-screen, everywhere.
I've seen this component in official HA components and thought that this is the proven solution.

Either I'm using it wrong somehow or it appears to me, that it contains bug when clicking/taping on mobile/touch devices.

In my observation the click is fired "twice". The first one is captured correctly and the dialog is opening, but after/during the dialog opening, second click is fired in the same position.
And if the position of the click is outside the dialog area, the dialog is instantly closed (even before it's rendered). Sometimes it's so fast, that "the outside" is everywhere (dialog not shown yet), so the hue-screen cannot be opened.

Another problem due to the same bug is when clicking the light-tile inside the dialog and the switch appears on the same position - light is toggled afterwards (#137)

**Comment by prabhjotsbhatia-ca** [comment]
Actually I've seen popups work on HA Android app but only for the first 4 cards. The desktop website works fine. 
I tried this, and couldn't click the 5th card; and then rearranged the 5th card to 3rd position, and the new 5th card stopped working. 
Here's a screen recording:

https://github.com/Gh61/lovelace-hue-like-light-card/assets/56749856/614f407f-0ec7-4dd9-bc71-235644f53a90

**Comment by Gh61** [comment]
Thank you for the recording.

**Comment by Gh61** [comment]
Fixed in the latest release.
