### ISSUE TITLE
Popup does not open with touch on Windows

### ISSUE THREAD

**Issue by jcmaxa** [Gh61/lovelace-hue-like-light-card#160]
A few weeks ago, the card popup stopped opening when using touch on a windows device. 

It happens regardless of the card container or how many cards are on the page.

I see this on Windows 11 with Chromium and Firefox browsers.

The popup does open with a mouse click.

The bug fix for issue #151 did not address this behavior.

**Comment by Gh61** [comment]
Thank you, luckily I have some older windows laptop with touch display.
So I try to revive this device and will test it.

**Comment by Gh61** [comment]
I believe this will be fixed, after implementing the HA original detection of tap, hold and double-tap.
I'd like to rewrite the action settings and functions all at once.

See [#167 - Extend and standardize actions](https://github.com/Gh61/lovelace-hue-like-light-card/issues/167)
