### ISSUE TITLE
Suggested README edit

### ISSUE THREAD

**Issue by terary** [Gh61/lovelace-hue-like-light-card#17]
Thank you for all your effort.  I am new with HA but love it so far. 
I struggled installing hue-like-light card, in part because I am new to this.   

I didn't understand this step so much and had to do my own thinking :) . 

It's not your responsibility to educate the public and I appreciate your efforts.   The one edit I suggest is explaining what the following statement means and where to get that information. 

I am happy to do a PR for you if that will help  

### Basic configuration
```yaml
type: custom:hue-like-light-card
entity: light.livingroom_color
```
Where `livingroom_color` is  the name/entity of some existing light

**Comment by Gh61** [comment]
Thank you for your suggestion.
I see, that the confusion comes from little experience with HA,
but I have no problem with pointing user to the right direction.
