### ISSUE TITLE
Styling customizations

### ISSUE THREAD

**Issue by bmcclure** [Gh61/lovelace-hue-like-light-card#18]
I love this card in general, but I'd like to make a few styling changes for how the main card looks on my dashboards. I've been trying to use card_mod to do this, and it works great while editing the card, but the card on my dashboard itself never gets the styling applied for some reason.

By contrast, card_mod is working for me on most other card types.

I'm curious if there is any known way to override the styling of the card?

The styles I'm attempting to apply, which look good while editing the card but do nothing when viewing it, are:

```
card_mod:
  style: |
    ha-icon {
      transform: scale(1.3) !important;
      position: static !important;
      top: auto !important;
      left: auto !important;
      margin-left: 1rem;
    }
    .tap-area {
      display:flex;
      align-items: center;
    }
    h2 {
      font-size: 1.2em;
      margin: 0 0 0 1rem !important;
    }
```

**Comment by Gh61** [comment]
Thanks for your bug reporting.

Apparently the way I transform the config values for this card is causing problem in loosing the `style` and/or `card_mod` values and no styling is then applied.
This will be fixed in the next release.
