### ISSUE TITLE
The possibility to define transparency for off color would be amazing!

### ISSUE THREAD

**Issue by AdamNaj** [Gh61/lovelace-hue-like-light-card#19]
I absolutely love the card! Most of lights all over my home are Hue based and this card makes it incredible to integrate it into the wall tablet dashboard! In fact, it motivated me to try to migrate from AppDaemon to Lovelace! The only thing I'm missing for it to blend with the dashboard is the ability to set the transparency for the off state!

I've seen that you've just added support for Card-mod maybe that's a way? 
I'm not sure I'm front-end versed enough to be able to do this right now.

A setting like `offTransparency` would work great!

The new WIP Lovelace Dashboard kind of brings unnecessary attention to the lights that are off:
![image](https://user-images.githubusercontent.com/1209953/230785441-b1bc8442-60ed-4b57-8beb-f941385e3590.png)

Old AppDaemon dashboard I'm in process of rebuilding into Lovelace:
![image](https://user-images.githubusercontent.com/1209953/230785569-0ee6efa1-95c8-4fb9-8a6c-6043beef97fb.png)

**Comment by Gh61** [comment]
Thank you for your suggestion.

I will implement `rgba(...)` format and HEX format with alpha channel.
I see this as minor change, so it will included in the next `1.4.0` release.

**Comment by Gh61** [comment]
Meanwhile you can try to set the `offColor` to `theme-color`, if the transparent color comes from your theme.
This should work already in the current version.

**Comment by AdamNaj** [comment]
I've tried that and it didn't seem to work in 1.3.0, but that's OK, I can wait :)
