### ISSUE TITLE
Missing option to change colour temperature on light

### ISSUE THREAD

**Issue by jomaskm** [Gh61/lovelace-hue-like-light-card#2]
I've read through the configuration and examples several times, but can't seem to find anything about this.

On the screenshot I've added a bedroom light. 
It is possible to change the colour temperature in the default light panel, but not in hue-like-light-card.

Am I missing something basic here?

![bilde](https://user-images.githubusercontent.com/30002504/180663841-5a643471-c619-4aa2-b060-f10f4c4da4cf.png)

**Comment by Gh61** [comment]
In the current version, there is no way to change color (or temparature). I am preparing this function for the next version. There will be some click actions, that you could use. You will have the choice of opening this system window (but only for one light on card), some toggling, setting some scene or opening new window, wich will have the functionality to set scenes and/or change light colors (I will also look on setting the color temperature).

**Comment by jomaskm** [comment]
Sounds good! Really liked the look of these cards. Compact and true to the "originals". Great job.

**Comment by tco35** [comment]
Great job ! But lack of temperature color picker is a pity.

**Comment by Gh61** [comment]
Resolved in the current [Release](https://github.com/Gh61/lovelace-hue-like-light-card/releases/tag/v1.4.0).
