### ISSUE TITLE
Version 1.7 not released?

### ISSUE THREAD

**Issue by ilianhris** [Gh61/lovelace-hue-like-light-card#205]
Hello. I see that can use apiId since version 1.7 but the latest can find is 1.6.1. Is there version 1.7?

**Comment by Gh61** [comment]
Hi, version 1.7 is not released yet. Sadly I'm really overwhelmed by work on other projects (mostly my primary job).
I'll still try to deliver the release till the end of this month as promised, but I'm starting to losing hope.
I'll do my best

Thank you for understanding
