### ISSUE TITLE
card mod doesnt seem to apply to this card

### ISSUE THREAD

**Issue by mcrummett** [Gh61/lovelace-hue-like-light-card#21]
For some reason card_mod doesn't seem to apply properly to this card?  When i do the below, the height is correct whilst in the configuration screen but no longer applies when viewing the dashboard normally.

```
card_mod:
  style: |
    ha-card { 
    min-height: 600px
    }
```

**Comment by Gh61** [comment]
Duplicate of #18.
Is already fixed, will be released in future version.

**Comment by mcrummett** [comment]
Ah sorry for the duplicate. Cheers!
