### ISSUE TITLE
Suggestion: Ability to edit 'icon' property as well as others when defining multiple entities.

### ISSUE THREAD

**Issue by samhoff20** [Gh61/lovelace-hue-like-light-card#23]
<img width="639" alt="Screenshot 2023-04-23 at 11 07 16 AM" src="https://user-images.githubusercontent.com/52685675/233847717-90a497ce-23d4-4091-bfff-a0d6aaa0636a.png">

I'd like to have the custom icons for the lights I've listed here as entities like you are able to define when it's a single 'entity:' :
'''
type: custom:hue-like-light-card
title: Downstairs
icon: hue:downstairs
entities:
  - light.dining
  - light.kitchen
 '''

**Comment by Gh61** [comment]
I can look into this, but currently, you can set icons for lights (and even for scenes) directly in the HA. This way the icon will be used for this entity everywhere in HA.
Can this solve your issue?

**Comment by samhoff20** [comment]
Ahh ok, I didn't realize that. Yea that would be fine, thanks.

**Comment by Gh61** [comment]
I am closing this issue as it looks like resolved.
