### ISSUE TITLE
Volume / media 

### ISSUE THREAD

**Issue by joeblack2k** [Gh61/lovelace-hue-like-light-card#248]
Hi, I love the light control card! I was wondering if it would be possible to add media devices in a similar simple way. Specifically, I’d like to have a slider for adjusting the volume and an on/off button for pausing/playing media, without displaying any media content. Is this something that could be implemented?

**Comment by Gh61** [comment]
Sorry, this card is focused solely on light controlling and support for any other entity types is not planned.

Maybe you can create somewhat similar card design, using another media player card a styling it with card_mod.
