### ISSUE TITLE
Can we create an animation on the icon?

### ISSUE THREAD

**Issue by maxhome75** [Gh61/lovelace-hue-like-light-card#25]
Good morning,
Thank you for your work.
Just a quick question.
Can we create an animation on the icon?
Style:
{% if is_state('light', 'on') %}
--icon-animation: spin 2s linear infinite;

I do not know how.
Thank you very much

**Comment by Gh61** [comment]
In the new version 1.4.0 (currently in development).
You will be able to rotate the icon with the folowing code (when using the card_mod):
```xaml
type: custom:hue-like-light-card
entity: light.study
style: |
  @keyframes spin {
    from {
        rotate:0deg;
    }
    to {
        rotate:360deg;
    }
  }
  ha-card.state-on ha-icon {
    animation: spin 2s linear infinite;
  }
```

**Comment by Gh61** [comment]
Resolved in the current [Release](https://github.com/Gh61/lovelace-hue-like-light-card/releases/tag/v1.4.0).
