### ISSUE TITLE
Support for Hue gradient light

### ISSUE THREAD

**Issue by LodeBo** [Gh61/lovelace-hue-like-light-card#26]
Love it !!!
Could it be possible to add the Hue gradient light ?

**Comment by Gh61** [comment]
Hi, thank you.

Can you please post some screenshots, how the official app looks like when controlling Hue Gradient Light (as i don't have this product on my own).
Also can you post attributes of light entity/entities from HA?

You can get them in your HA, go to **Developer Tools**, **then States** and **search** for your light(s).
Click on it to open detail of the entity and make me a printscreen of attributes.
Thank you

**Comment by Gh61** [comment]
Due to zero information on this topic, this issue is closed.
Feel free to reopen this, if you need.

**Comment by RubenDebusscher** [comment]
Just commenting on this request, as I was looking for this as well, and was hoping this could be impemented.  I believe the request is mainly to accomodate the multiple zones the gradient lightstrip consists of.  If I understand the product documentation of the different hue gradient product  correctly, this setup is also used for the Hue Festavia christmas lights.
![WhatsApp Image 2024-10-30 at 16 39 04_bb4f21d5](https://github.com/user-attachments/assets/97aa54db-550b-4fa8-b51f-cd4d66263fff)
![WhatsApp Image 2024-10-30 at 16 39 04_07fd3641](https://github.com/user-attachments/assets/7c13b903-e195-44b9-8e2e-051104f07799)
![WhatsApp Image 2024-10-30 at 16 39 04_50a1d9e3](https://github.com/user-attachments/assets/23a7d48a-372d-4798-8eb5-f962bcf81504)


The last image illustrates 3 diferent options:
The first setting allows to set 3 points, with a line between them, which follows this gradient
The second option makes this same gradient, but mirrors it across the lenght of the strip (essentially going ABCBA).
The last option allows for 5 different points, that are repeated across the strip. (I believe when I bought the strip there were only 3 zones, so they possibly added more through firmware updates).

I believe adding this would open a whole new world of automations for when you have friends over or a party, where an automation could generate a different color for every section every few seconds

**Comment by Gh61** [comment]
Thank you.
According to the screenshot of entity attributes from HA, it seems like all the parts are represented by one single light in Home Assistant. Is that true?
If so, then I cannot do anything about it, unless there's some way to control individual parts of the lights strip over HA.

This card provides only UI for already existing possibilities in HA.

**Comment by RubenDebusscher** [comment]
I see, it seems it would first require an update for the Hue Integration itself to include the gradients they implemented in the V2 API.
