### ISSUE TITLE
Is there a way to disable scenes?

### ISSUE THREAD

**Issue by Gherry777** [Gh61/lovelace-hue-like-light-card#276]
Hello,
I like the addon a lot, but I would like the ability to disable scenes.
Sometimes I just want to change the color of one light (or a group), or I want to be able to disable the scene control for a specific device (or group of devices).

A toggle or a command in yaml (like scene_disable: yes) would really be nice.

Anyway, I think the addon is great!

**Comment by Gh61** [comment]
You can use: `scenes: []` in config of your card.

There will still be a little empty space in the place, where scenes are supposed to be (this space is left visible, in order for the color picker to have enough space to open).

**Comment by Gherry777** [comment]
Ok, thank you!
