### ISSUE TITLE
Display current Scene name?

### ISSUE THREAD

**Issue by nitras** [Gh61/lovelace-hue-like-light-card#285]
Hi. Great addition to Home Assistant.
However I fail to understand how I display the current active scene as a name on my light buttons.
Thank you.

**Comment by Gh61** [comment]
Sorry, that would not be possible, as Home Assistant does not provide current active scene (unlike hue for example).

**Comment by nitras** [comment]
Thanks, too bad. As my hue scenes are stored in the HA's scenes folder, I thought It was easy to read them in.
Honestly would be a nice feature to have (for me personally — at least)
