### ISSUE TITLE
Scenes only showing default icon

### ISSUE THREAD

**Issue by RedwoodNL** [Gh61/lovelace-hue-like-light-card#294]
![Scenes](https://github.com/user-attachments/assets/299e24f3-349e-41fb-896c-e2c45e5e1332)

As you can see, all scenes use a default icon and they don't show the icons as they are in the app. 
In your examples the images are seen in the scenes.

![scenes example](https://github.com/user-attachments/assets/354dfa6a-3832-4408-b4e6-0ce201740a51)

Code i'm using:

type: custom:hue-like-light-card
area: Woonkamer
icon: mdi:sofa
offColor: "#363636"
allowZero: true

**Comment by Gh61** [comment]
You'll need to have `entity_picture` attributes set on individual entities.
See [this issue](https://github.com/Gh61/lovelace-hue-like-light-card/issues/126) for more info.
