### ISSUE TITLE
Hass hue icons

### ISSUE THREAD

**Issue by arallsopp** [Gh61/lovelace-hue-like-light-card#3]
Hey. This would look great paired with [hass-hue-icons](https://github.com/arallsopp/hass-hue-icons). Wonder if there's a way to bundle both together?

Feel free to use them in your screenshots.

**Comment by Gh61** [comment]
> Feel free to use them in your screenshots.

Thank you, I will!

Maybe I can add some detection and integration with these icons (in [Automatic icon](https://github.com/Gh61/lovelace-hue-like-light-card#automatic-icon)) and I can mention it in readme. (Maybe you can then do the same?)

Currently I have little free time, so I cannot say when this edits will happen, but I'll keep that in mind.

**Comment by Gh61** [comment]
Resolved in the current [Release](https://github.com/Gh61/lovelace-hue-like-light-card/releases/tag/v1.4.1).
