### ISSUE TITLE
Use mushroom styled slider

### ISSUE THREAD

**Issue by Greenphlem** [Gh61/lovelace-hue-like-light-card#31]
Hello!

Is there any way to change the style of the slider to have a bigger touch target? At the moment, the touch target is too small for my preference. In the screenshot below is a comparison of the current hue-card sliders vs Mushroom cards.

![Screenshot_20230704_110728_Home Assistant](https://github.com/Gh61/lovelace-hue-like-light-card/assets/3390436/88bb2c58-377e-4112-a697-e9c30e869eee)

**Comment by Gh61** [comment]
You can style the card as you wish using the [card mod](https://github.com/thomasloven/lovelace-card-mod).
You can create style which will enlarge the slider pointer (using `transform:scale(2)` for example).

**Comment by ITensEI** [comment]
I would also love to see a mushroom style slider as it's a bit more mobile friendly.
@Gh61 if you have the CSS for card_mod to make it look like the mushroom one please share it.

**Comment by Gh61** [comment]
Thank you @ITensEI, I'll look into some possibilities to make the slider look like mushroom one.

**Comment by Greenphlem** [comment]
Woo! Thank you @Gh61

**Comment by magnonan** [comment]
Is there a way to change the background color and text color?   I can't get it to work using card mod.

**Comment by Gh61** [comment]
@magnonan 
No, color of text a background is changed based on the actual color of light.
This is the main reason for this card to exists.

**Comment by Gh61** [comment]
Will be part of the next release.
For configuration see https://github.com/Gh61/lovelace-hue-like-light-card#slider-type

**Comment by Greenphlem** [comment]
Thank you so much!! This is great.
