### ISSUE TITLE
Feature: Color-picker - Change multiple lights at once

### ISSUE THREAD

**Issue by paulswerker** [Gh61/lovelace-hue-like-light-card#32]
I really appreciate the dashboard's current design! However, I've noticed that it lacks a feature present in the hue app where you can view all the different lights and their current colors. In the app, you can easily move them together by dragging them on top of each other. With multiple lamps on the dashboard, it becomes a bit tedious to individually adjust each lamp to achieve matching colors.

**Comment by Gh61** [comment]
Don't worry, this feature is totally planned in one of the future releases! But it may take some time.

**Comment by prabhjotsbhatia-ca** [comment]
Looking forward to it! In the meantime I have been working around this by adding the group Entity to the entities list as well: 
<img width="498" alt="image" src="https://github.com/Gh61/lovelace-hue-like-light-card/assets/56749856/10eba471-fb37-47bc-af01-15807db257a6">

**Comment by kwbeck** [comment]
I have been using the same work around (adding the group Entity), which works well for being able to change the color of all the lights in a room at once.  However, adding the group Entity throws off the count of lights in the room by 1, since it counts the group Entity as a light.  

I had been looking for a way to do something like (%s -1) in the count, but couldn't get that to work.  This will mostly fix the problem, I believe, but @gh61, if you have any suggestions or ideas for how to address the light count issue, I would love to have your input.

**Comment by Gh61** [comment]
The possibility to change color of multiple lights at once (this issue) will be soon available (it will be in the new version, I am working on right now). The latest release date is 2024/3, but I hope it will be released sooner.
I believe you will no longer need the group entity then.

**Comment by adynis** [comment]
Do you have a screenshot or docu how it should work ? I'm not sure where should I find the result of this fix (I just updated to 1.7.1). Thanks.

**Comment by Gh61** [comment]
It's working the same way as in official hue application (and as described in first post in this issue). When you move the color picker of one light over the picker of other light and let go, you will join them to create one picker for both (all joined) lights.
Then you control the color for all lights at once.
You can split the picker again by clicking on specific light in the horizontal list.

**Comment by adynis** [comment]
Thanks for explaining, maybe I need to restart my HA to be sure ... Currently I see no change yet 
![image](https://github.com/Gh61/lovelace-hue-like-light-card/assets/10837368/814239e6-8af8-478c-a4f6-407aefa0680e)
![image](https://github.com/Gh61/lovelace-hue-like-light-card/assets/10837368/d137eb6c-85b7-4509-8095-7e07bd816cea)

**Comment by Gh61** [comment]
Looks like you still have loaded the old version on your phone.
You can force the reload by going closing the HA app, going into app detail and clearing the cache.
Then it should reload the latest version.

**Comment by adynis** [comment]
Waaaaw, suuperrr !!! Indeed, was the phone casche, sorry for my comments :) Thanks a lot, it looks great !!! 🥇
