### ISSUE TITLE
Color control for non hue brand lights?

### ISSUE THREAD

**Issue by teddy-ptmedia** [Gh61/lovelace-hue-like-light-card#35]
It seems only my hue branded lights allow setting the colors. All other lights only show on/off/brightness. 

Is it not possible to use non hue branded lights with this?

**Comment by Gh61** [comment]
Hi, it should work for all lights no matter the brand.

Can you please post attributes of your light/s? 
There's probably something unusual, thus the color-changing possibility is not recognized.

When you open your **HA**, go to **Developer Tools**, then **States** and **search** for your hue plug **light**.
**Click** on it to open **detail** of the entity and make me a printscreen of **attributes**.
It should look something like this:
![image](https://user-images.githubusercontent.com/10837736/217230108-8b4b6fd8-3378-4180-a918-68d4ad52aef0.png)

**Comment by teddy-ptmedia** [comment]
One of my non hue lights
![IMG_1292](https://github.com/Gh61/lovelace-hue-like-light-card/assets/66155199/2f999215-deb1-43f8-bd5c-03a104a46d8e)

**Comment by Gh61** [comment]
Thank you.

It's odd, that it's not working, as this should already be recognized correctly.
I'll do some testing a try to make some fix for this issue.

**Comment by teddy-ptmedia** [comment]
> Thank you.
> 
> It's odd, that it's not working, as this should already be recognized correctly. I'll do some testing a try to make some fix for this issue.

Hello friend! Any luck?

**Comment by teddy-ptmedia** [comment]
> Thank you.
> 
> It's odd, that it's not working, as this should already be recognized correctly. I'll do some testing a try to make some fix for this issue.

I have looked at this further and I still can not figure out why it is not operating as expected. Have you had the chance to take any more of a look into it? Thank you!

**Comment by Gh61** [comment]
I'm quite busy lately.
I'll look into in as soon as I can. Give me few days.

**Comment by Gh61** [comment]
It appears, that your light integration is not correctly implemented.
According to [documentation](https://developers.home-assistant.io/docs/core/entity/light/), the value `brightness`, if used in `supported_color_modes`, should be the only value here.
So the light is currently recognized as if it only supports brightness change.

I will make some changes, to recognize other features even on lights that are not correctly implemented.
It should be reported to the developer of your light's brand integration, as some other components can have the same issue.

**Comment by teddy-ptmedia** [comment]
Thank you. The lights are Tuya based. On Sep 3, 2023, at 12:55 AM, Tomáš Zenkner ***@***.***> wrote:﻿
It appears, that your light integration is not correctly implemented.
According to documentation, the value brightness, if used in supported_color_modes, should be the only value here.
So the light is currently recognized as if it only supports brightness change.
I will make some changes, to recognize other features even on lights that are not correctly implemented.
It should be reported to the developer of your light's brand integration, as some other components can have the same issue.

**Comment by Gh61** [comment]
Resolved in the current [Release](https://github.com/Gh61/lovelace-hue-like-light-card/releases/tag/v1.4.2).
