### ISSUE TITLE
Support theme background colors

### ISSUE THREAD

**Issue by rtyk** [Gh61/lovelace-hue-like-light-card#4]
A quick suggestion.  Depending on the HA theme and background color, it is difficult to find an 'offColor' that works well across different background colors.  
Would it be possible to expand the 'offColor' key to support an opaque mode or some other method to use the background as a base for the card color? Would this be problematic in the transitition to 'defaultColor'?

**Comment by Gh61** [comment]
Thank you for suggestion, in fact I'm already planning add the 'theme' possibility for colors, where it makes sense.
I am planing to release minor version with some small adjustments pretty soon, it's very likely, this feature will be in there.

**Comment by rtyk** [comment]
Happy to hear you already had it on the plan.  Looking forward to the release.  
Thanks

**Comment by Gh61** [comment]
Let's keep it open, until the release with this feature is out.
