### ISSUE TITLE
Toggle room instead of all lights with switch

### ISSUE THREAD

**Issue by baurmatt** [Gh61/lovelace-hue-like-light-card#55]
First of all: Thank you very much! I've been dreaming of a hue style card for years and yours is close to perfect!

When implementing your card into my setup, I've realized that hitting the switch to enable/disable all lights doesn't trigger them simultaneously as the official Hue app does. This is probably because the card triggers each light individually, instead of using the Hue provided room entity. My feature request would be: Can we please get the entity configurable that's trigger on hitting the switch?

Thanks in advance!

**Comment by baurmatt** [comment]
This should probably also be configurable for the slider :thinking:

**Comment by Gh61** [comment]
Thank you. 

Interesting idea. I can see, that if you are controlling bigger number of lights, there could be some delay.

I'll try to look into possibilities to manipulate with all lights at once or as you suggested - option to set some room entity for changing everything in given room.

**Comment by Gh61** [comment]
I did some testing and the only way I can get close to syncing all lights turning on/off and changing brightness simultaneously is using the zone/room entity as you suggested (in case of Hue integration the entity is disabled by default).
I will add the option to set this entity to card, for smoother experience.

**Comment by Gh61** [comment]
This feature was implemented in PR #123 and will be in the next release.
