### ISSUE TITLE
Hue Dynamic Scenes

### ISSUE THREAD

**Issue by andrei-micu-ro** [Gh61/lovelace-hue-like-light-card#6]
Hello,

One great addition would be adding support for the HUE Dynamic Scenes.
I'm only using Hue so I "hacked" the code to call a different service (line 77 in js file):
`this._hass.callService("hue","activate_scene",{entity_id:this._config.entity,dynamic:true,transition:10,speed:40})`

I also added transition and speed values.

For me this works well but it's not configurable. For others it would be a good idea to:
- Have a toggle parameter to switch between normal scene triggering or Hue (using the new hue.activate_scene service)
- Add parameters for:
  - dynamic scene - boolean
  - transition time - integer
  - speed - integer

**Comment by Gh61** [comment]
Hi,

thank you for your feature proposal.
I will look for different ways how to activate scenes for different light platforms, so I can come with some settings that can be used generally.
