### ISSUE TITLE
Feature Request: Official hue scenes

### ISSUE THREAD

**Issue by Hypfer** [Gh61/lovelace-hue-like-light-card#69]
Hi there,

I've spent the last few days building a custom_component implementing the scene functionality of hue using all the scenes from the official hue scene gallery. Hue scenes and HA scenes are actually quite a bit different with the Hue ones being presets for a state that can be applied to a bunch of entities and the HA ones being a set of states for a specific set of entities

I'm now wondering how a UI for that could look like, as right now, it's just a bunch of services.

You can find the component here:
https://github.com/Hypfer/hass-scene_presets

It features images for all scene presets that have been AI generated to avoid all the legal issues.
It also provides services that simulate the dynamic scene feature of hue.

I'm of course posting it here mostly in the hope that you find it interesting so that I can be lazy on the UI part but please don't feel pressured to do anything with it. After all it's I who wants to see something happen so it's also I that is responsible for building it.
Still I figured that you might find it cool as well but if not feel free to close the issue

**Comment by Greenphlem** [comment]
This would be great! +1 from me if this could get implemented

**Comment by Gh61** [comment]
Hello,

I see this as an interesting project, thank you for reaching me.

If I get this correctly, the reason for your integration is the new hue policy to use account with official hue app. So in your scenario you'll have your lights integrated over ZigBee, making the og hue scenes unavailable. Did I get this correctly?

I'm still thinking about the right approach to connect our two projects in a meaningful way. For now I think about two usages.

Firstly, I really like these images you have for every scene. And I would like to create some detection algorithm to my card for original hue scenes (based on their name/id - I know, I'll be dealing with localization, but I'll try anyway), based on which I'd like to use these images (with your permission) as icons for these scenes.

The second scenario, I'm thinking of, is to add some config option to define scenes/presets from your integration and allow to activate them from my [hue-screen](https://github.com/Gh61/lovelace-hue-like-light-card#hue-screen) additionally to classic HA or original hue scenes.

e.g.
```yaml
type: custom:hue-like-light-card
entities:
  - light.kitchen_desk1
  - light.kitchen_desk2
scene_presets:
  - tokyo
  - blossom
# - (other presets from your integration)
```

In the future I'm also planning to add the classic play/stop button for scenes - allowing to start animation on scenes, which supports this feature. So this would also be compatible.

So maybe when you polish your project a little and release it on HACS store, I can add this option.
I have a little doubt whether you will keep your project maintained enough, when I see your comment that most of the code has been written by AI. What are your plans about this?

PS:
I don't know how are you animating the colors in your integration, but please mind, that you could introduce serious load on `recorder` that will cause huge amount of inserts to internal database. This can be problem on some systems (mainly the one's running on SD card - such as raspberry pi's).
I've run into this issue, when trying to run this [Color loop](https://community.home-assistant.io/t/color-loop-blueprint-with-configurable-colors-and-transition-time/427682). I ended up with disabling history in recorder for selected lights.

**Comment by Hypfer** [comment]
> So in your scenario you'll have your lights integrated over ZigBee, making the og hue scenes unavailable. Did I get this correctly?

Yep, exactly. For HA, they're just `light` entities with no special features.

>  based on which I'd like to use these images (with your permission) as icons for these scenes.

Yeah! Sure, knock yourself out :)

> What are your plans about this?

That's a good question and you're right to be doubtful there. I honestly have no idea. I did briefly look into what is required to get it officially into HACS but then quickly dropped that thought due to.. interesting requirements.
While I do really like HA, corporate compliance checkboxes just aren't really my cup of tea and they do love those very much.

Anyway, I do totally understand your requirement there. That's a more than reasonable stance to take.

When it comes to the static scene presets, it would also be possible to implemented that client-side (e.g. as a feature of the card).
That wouldn't allow you to use them in automations but otoh it also gets rid of the requirement for a custom component.

**Comment by Hypfer** [comment]
Okay, after revisiting the problem and learning that custom_components can provide custom panels, I think that such a custom panel would be the correct way forward for me.

Therefore, I'm closing the ticket. Thanks for taking the time to consider this! :)

**Comment by Gh61** [comment]
Alright.
Thank you anyway for introducing your project. I'll be watching your progress as I consider migrating to pure zigbee myself.
Maybe in some future I'll add some option to use your integration.

**Comment by Gh61** [comment]
Hi @Hypfer. Just so you know, thanks to @docloulou and @aidanlloydtucker this has been just implemented and will be available in the upcoming release.
