### ISSUE TITLE
Example of complete Hue Screen

### ISSUE THREAD

**Issue by Wytoo** [Gh61/lovelace-hue-like-light-card#8]
Hi there

Maybe I'm to dumb to figure it out, but I can't seem to get the Hue Screen to work as you've posted it in the manual.
What do I have to code to have it done like that?

What I want to do is have the scene only apply to a single group withing a room which has two groups. Like i.e. I have 7 lights within a room. 2 for the sink within a group called that and the rest of them for a group called table. Whenever I turn on a scene now, it does that for the whole room.

**Comment by Gh61** [comment]
I suppose, that the issue is resolved.
