### ISSUE TITLE
Slider with Mushroom - where ?

### ISSUE THREAD

**Issue by whyisthisbroken** [Gh61/lovelace-hue-like-light-card#82]
Hey, i wonder where i find V1.5 - is it included now or must we wait for release ? 
https://github.com/Gh61/lovelace-hue-like-light-card/commit/1fdaf4feb8c27a5fdae969db328681dfd67aac77

**Comment by Gh61** [comment]
Hi, yes, the 1.5 release is not out yet. I'd like to add one or two more things before releasing, but I've been in a little rush lately.
I suppose the release could be out till the end of the next week.
