### ISSUE TITLE
Additional Function: HoldAction?

### ISSUE THREAD

**Issue by YuulGer** [Gh61/lovelace-hue-like-light-card#95]
Hey there!

First things first: I really love what you created for HA! It really helps me organising and controlling my lights! 🥇

I just wondered while using your card, if it would be possible to add a HoldAction? 
I'd like to use a ClickAction to turn the lights on and off and use a HoldAction to open the HueScreen. Do you think something like that would be possible in the future or is it already possible? Couldn't find anything about that in your readme :(

Would really appreciate hearing from you! 👍

**Comment by Gh61** [comment]
Hi,

it's a great idea, I'll look into it, shouldn't be much work.

**Comment by YuulGer** [comment]
Thanks for the quick response! :)

**Comment by Gh61** [comment]
This feature will be in the next release.
