### ISSUE TITLE
Slider Problem

### ISSUE THREAD

**Issue by YuulGer** [Gh61/lovelace-hue-like-light-card#96]
Sorry to bother you again:

It could be that i'm getting something wrong, but the function to hide the slider isn't working for me :(

![Slider_problem_Hue_like_light_card](https://github.com/Gh61/lovelace-hue-like-light-card/assets/147979055/66fce58a-8d5a-4abc-b199-81ec6041b2ce)

Thanks you in advance for your help :)

**Comment by Gh61** [comment]
Looks like you have the old version of card (as there is no description under the title).
The feature to customize the slider is only in 1.5.0+

**Comment by YuulGer** [comment]
thank you. 
had to reinstall. Now it's working! 💯
